trigger:
  tags:
    include:
    - "*"
  branches:
    include:
    - main
    - feature/*
pr:
- main

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: spydersoft-gh
      name: spydersoft-consulting/azure-devops-templates

extends:
  template: pipelines/dotnet-library-build/v1.yml@templates
  parameters:
    projectsToBuild: src/Spydersoft.Core.Hosting/Spydersoft.Core.Hosting/Spydersoft.Core.Hosting.csproj
    projectsToPack: src/Spydersoft.Core.Hosting/Spydersoft.Core.Hosting/Spydersoft.Core.Hosting.csproj
    executeTests: true
    # If it's a PR or a build from main (not a tag) then don't publish to Nuget
    ${{ if or(eq(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranchName'], 'main')) }}:
      publishToNuget: false
    ${{ else }}:
      publishToNuget: true
    dotnetSdk: "8.0.x"
    gitVersionVersion: "6.x"
    nugetConfigPath: $(Build.SourcesDirectory)/src/nuget.config
    externalPublishFeed: SpydersoftDevelop
    executeSonar: false
    sonarEndpointName: sonarcloud-internal
    sonarProjectKey: asp_core_libraries
    sonarProjectName: Core Libraries
    sonarExtraProperties: |
      sonar.projectKey=asp_core_libraries
      sonar.sources=./src/
      sonar.tests=./src/**/*.UnitTests/